"""first revision

Revision ID: 4ced6aedafd0
Revises: 
Create Date: 2022-11-12 00:41:57.976120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ced6aedafd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza_types',
    sa.Column('_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pizza_type_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('Chicken', 'Classic', 'Supreme', 'Veggie', name='categoryenum'), nullable=True),
    sa.Column('ingredients', sa.String(), nullable=False),
    )
    op.create_index(op.f('ix_pizza_types_pizza_type_id'), 'pizza_types', ['pizza_type_id'], unique=True)
    op.create_table('orders',
    sa.Column('_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_table('pizzas',
    sa.Column('_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pizza_id', sa.String(), nullable=False),
    sa.Column('pizza_type_id', sa.String(), nullable=False),
    sa.Column('size', sa.String(length=3), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=7, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['pizza_type_id'], ['pizza_types.pizza_type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pizza_id')
    )
    op.create_index(op.f('ix_pizzas_pizza_id'), 'pizzas', ['pizza_id'], unique=True)
    op.create_table('order_details',
    sa.Column('_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_details_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pizza_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.pizza_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_details_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
